import transformCollectionObject from '@/lib/sanity/transform/collectionObject';

describe('transformCollectionObject', () => {
  it('transforms collectionObject raw source correctly', () => {
    const rawSource = {
      _createdAt: '2023-11-20T17:08:45Z',
      _id: 'collection_object_149224',
      _rev: 'tdSEgP3G53V2majpbdhO36',
      _type: 'collectionObject',
      _updatedAt: '2023-11-20T17:08:50Z',
      accessionDate: '1975-01-14T05:00:00.000Z',
      accessionNumber: '74.212.4',
      accessionNumberSort: '   1974    212     4',
      approvalsMask: null,
      classification: 'Tool',
      collectionId: 10,
      completeness: 62,
      constituents: [
        {
          _key: 'LsoZKD2Q',
          artist: {
            _createdAt: '2023-11-20T17:08:44Z',
            _id: 'collection_artist_21114',
            _rev: 'Uckd0KyIppGAIvpptVFZCf',
            _type: 'collectionArtist',
            _updatedAt: '2023-11-20T17:08:44Z',
            dateAdded: '2020-07-31T04:00:00.000Z',
            dates: '',
            endYear: null,
            name: 'Alaska Native',
            nationality: '',
            startYear: null,
          },
          prefix: null,
          role: {
            _createdAt: '2023-10-25T16:00:44Z',
            _id: 'collection_role_224943',
            _rev: 'Uckd0KyIppGAIvpptVFZCf',
            _type: 'collectionRole',
            _updatedAt: '2023-10-25T16:00:44Z',
            name: 'Culture',
          },
          suffix: null,
        },
      ],
      copyright: null,
      copyrightRestricted: 0,
      creditLine: 'Gift of Mr. and Mrs. John A. Friede',
      dateAdded: '2010-03-10T05:00:00.000Z',
      description: null,
      dimensions: '2 7/8 in. or (7.4 cm)',
      dynasty: null,
      edition: null,
      images: [
        {
          _key: 'ucpMWly4',
          credit: 'Brooklyn Museum photograph',
          date: null,
          dateAdded: '2011-09-02T04:00:00.000Z',
          derivatives: [
            {
              _key: 'QvrdroDl',
              createdAt: '2023-09-26T18:52:32.000Z',
              height: 96,
              size: '0',
              updatedAt: null,
              width: 75,
            },
            {
              _key: 'VtaRbDTW',
              createdAt: '2023-09-26T18:52:32.000Z',
              height: 192,
              size: '1',
              updatedAt: null,
              width: 151,
            },
            {
              _key: 'ST33wGC3',
              createdAt: '2023-09-26T18:52:32.000Z',
              height: 384,
              size: '2',
              updatedAt: null,
              width: 303,
            },
            {
              _key: 'L7E8D6Wg',
              createdAt: '2023-09-26T18:52:32.000Z',
              height: 768,
              size: '3',
              updatedAt: null,
              width: 607,
            },
            {
              _key: 'eWgf3Rmj',
              createdAt: '2023-09-26T18:52:32.000Z',
              height: 1536,
              size: '4',
              updatedAt: null,
              width: 1214,
            },
          ],
          description: null,
          filename: '74.212.4_bw.jpg',
          isColor: null,
          loadDate: '2016-11-07T05:00:00.000Z',
          rank: 1,
          status: 'active',
          updatedAt: '2023-08-05T08:01:47.000Z',
          view: 'overall',
        },
        {
          _key: 'NZhzg4Gd',
          credit: 'Brooklyn Museum photograph',
          date: '2011',
          dateAdded: '2011-11-29T05:00:00.000Z',
          derivatives: [
            {
              _key: 'pbXOFyR4',
              createdAt: '2023-09-26T18:52:32.000Z',
              height: 63,
              size: '0',
              updatedAt: null,
              width: 96,
            },
            {
              _key: 'mcJcqKDL',
              createdAt: '2023-09-26T18:52:32.000Z',
              height: 127,
              size: '1',
              updatedAt: null,
              width: 192,
            },
            {
              _key: 'waGBvjVM',
              createdAt: '2023-09-26T18:52:32.000Z',
              height: 255,
              size: '2',
              updatedAt: null,
              width: 384,
            },
            {
              _key: 'e1mDhyih',
              createdAt: '2023-09-26T18:52:32.000Z',
              height: 510,
              size: '3',
              updatedAt: null,
              width: 768,
            },
            {
              _key: 'CIdH72fK',
              createdAt: '2023-09-26T18:52:32.000Z',
              height: 1000,
              size: '4',
              updatedAt: null,
              width: 1504,
            },
          ],
          description: null,
          filename: 'CUR.74.212.4.jpg',
          isColor: null,
          loadDate: '2016-11-08T05:00:00.000Z',
          rank: 2,
          status: 'active',
          updatedAt: '2023-08-05T08:01:47.000Z',
          view: 'overall',
        },
      ],
      inscribed: null,
      markings: null,
      medium: 'Ivory, wood, leather',
      museumLocationId: 28336,
      objectDate: 'late 19th-early 20th century',
      objectDateBegin: 1868,
      objectDateEnd: 1933,
      objectStatus: 'PERMANENT COLLECTION',
      period: null,
      portfolio: null,
      provenance: null,
      publicAccess: 1,
      random: 136,
      rightsTypeId: 9,
      section: '',
      signed: null,
      state: null,
      title: 'Hook-shaped Toggle',
      updatedAt: '2023-01-23T09:01:40.000Z',
      visible: 1,
    };

    const expected = {
      _id: 'collection_object_149224',
      type: 'collectionObject',
      url: 'https://brooklynmuseum.org/opencollection/objects/149224',
      title: 'Hook-shaped Toggle',
      startYear: 1868,
      endYear: 1933,
      collection: 'Arts of the Americas',
      museumLocation: 'Luce Visible Storage and Study Center, 5th Floor, Paper Alcove, Drawer Unit',
      visible: true,
      publicAccess: true,
      searchText: '74.212.4',
      classification: 'Tool',
      constituents: [
        {
          id: '21114',
          name: 'Alaska Native',
          role: 'Culture',
        },
      ],
      imageUrl:
        'https://d1lfxha3ugu3d4.cloudfront.net/images/opencollection/objects/size0/74.212.4_bw.jpg',
      rawSource,
    };
    const result = transformCollectionObject(rawSource, 'https://brooklynmuseum.org');
    expect(result).toEqual(expected);
  });

  it('transforms collectionObject raw source correctly', () => {
    const rawSource = {
      _createdAt: '2023-11-20T17:08:45Z',
      _id: 'collection_object_90411',
      _rev: 'tdSEgP3G53V2majpbdhNom',
      _type: 'collectionObject',
      _updatedAt: '2023-11-20T17:08:50Z',
      accessionDate: '1966-12-07T05:00:00.000Z',
      accessionNumber: '66.178.3',
      accessionNumberSort: '   1966    178     3',
      approvalsMask: null,
      classification: '(not assigned)',
      collectionId: 4,
      completeness: 18,
      constituents: [
        {
          _key: 'iMiu6sPL',
          artist: {
            _createdAt: '2023-11-20T17:08:44Z',
            _id: 'collection_artist_14082',
            _rev: 'Uckd0KyIppGAIvpptVFZCf',
            _type: 'collectionArtist',
            _updatedAt: '2023-11-20T17:08:44Z',
            dateAdded: '2017-08-04T04:00:00.000Z',
            dates: 'French',
            endYear: null,
            name: 'E. Sanglan',
            nationality: 'French',
            startYear: null,
          },
          prefix: null,
          role: {
            _createdAt: '2023-10-25T16:00:44Z',
            _id: 'collection_role_224950',
            _rev: 'Uckd0KyIppGAIvpptVFZCf',
            _type: 'collectionRole',
            _updatedAt: '2023-10-25T16:00:44Z',
            name: 'Artist',
          },
          suffix: null,
        },
        {
          _key: 'dyZ9DLY9',
          artist: {
            _createdAt: '2023-11-20T17:08:44Z',
            _id: 'collection_artist_14082',
            _rev: 'Uckd0KyIppGAIvpptVFZCf',
            _type: 'collectionArtist',
            _updatedAt: '2023-11-20T17:08:44Z',
            dateAdded: '2017-08-04T04:00:00.000Z',
            dates: 'French',
            endYear: null,
            name: 'E. Sanglan',
            nationality: 'French',
            startYear: null,
          },
          prefix: null,
          role: {
            _createdAt: '2023-10-25T16:00:44Z',
            _id: 'collection_role_224954',
            _rev: 'Uckd0KyIppGAIvpptVFZCf',
            _type: 'collectionRole',
            _updatedAt: '2023-10-25T16:00:44Z',
            name: 'Decorator',
          },
          suffix: null,
        },
      ],
      copyright: null,
      copyrightRestricted: 0,
      creditLine: 'Gift of Mr. and Mrs. Dudley T. Easby Jr.',
      dateAdded: '2010-03-10T05:00:00.000Z',
      description: null,
      dimensions: '21 x 8 1/2 in. (53.3 x 21.6 cm)',
      dynasty: null,
      edition: null,
      images: [],
      inscribed: 'no inscriptions',
      markings:
        'on lower part of bowl near base of tree:  "E. Sanglan", signature in intaglio.  Stamped into base: "3784 / GARANTI / ETAIN / LV"',
      medium: 'Bronzed pewter',
      museumLocationId: 26304,
      objectDate: 'ca. 1900',
      objectDateBegin: 1898,
      objectDateEnd: 1902,
      objectStatus: 'PERMANENT COLLECTION',
      period: null,
      portfolio: null,
      provenance: null,
      publicAccess: 1,
      random: 103,
      rightsTypeId: 9,
      section: '',
      signed: 'no signature',
      state: null,
      title: 'Oil Lamp',
      updatedAt: '2023-01-23T09:01:40.000Z',
      visible: 1,
    };
    const expected = {
      _id: 'collection_object_90411',
      type: 'collectionObject',
      url: 'https://brooklynmuseum.org/opencollection/objects/90411',
      title: 'Oil Lamp',
      startYear: 1898,
      endYear: 1902,
      collection: 'Decorative Arts',
      visible: true,
      publicAccess: true,
      searchText: '66.178.3',
      constituents: [
        {
          dates: 'French',
          id: '14082',
          name: 'E. Sanglan',
          role: 'Artist',
        },
        {
          dates: 'French',
          id: '14082',
          name: 'E. Sanglan',
          role: 'Decorator',
        },
      ],
      rawSource,
    };
    const result = transformCollectionObject(rawSource, 'https://brooklynmuseum.org');
    expect(result).toEqual(expected);
  });
});
